#!/bin/bash
#PBS -N sample_summarizer
#PBS -J 1-20
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=1
#PBS -e sample_summarizer.err
#PBS -o sample_summarizer.log

module load Anaconda3
source activate tierpsy

cd $PBS_O_WORKDIR
FILESSOURCE="./files2process.txt"

echo "Username: " `whoami`
FSOURCE=$(awk "NR==$PBS_ARRAY_INDEX" $FILESSOURCE)
echo $FSOURCE
eval $FSOURCE >& ./pbs_output/output.$PBS_ARRAY_INDEX
exit 0
